// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKknzkKsTEzQYkHAhkvvJ0RAfUuLP2NZU',
    appId: '1:838439486018:web:5a31e2fb662a3ee80c63db',
    messagingSenderId: '838439486018',
    projectId: 'minimal-chat-app-692db',
    authDomain: 'minimal-chat-app-692db.firebaseapp.com',
    storageBucket: 'minimal-chat-app-692db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMvjSuH7S4OQfw31v_r3K5x0-ZKSt43sU',
    appId: '1:838439486018:android:22a22f4302ac28c80c63db',
    messagingSenderId: '838439486018',
    projectId: 'minimal-chat-app-692db',
    storageBucket: 'minimal-chat-app-692db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhsTUTHbhAU-6xkBpx_R8othLC-rpOVMs',
    appId: '1:838439486018:ios:b9789180274da1020c63db',
    messagingSenderId: '838439486018',
    projectId: 'minimal-chat-app-692db',
    storageBucket: 'minimal-chat-app-692db.firebasestorage.app',
    iosBundleId: 'com.example.myChartApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhsTUTHbhAU-6xkBpx_R8othLC-rpOVMs',
    appId: '1:838439486018:ios:b9789180274da1020c63db',
    messagingSenderId: '838439486018',
    projectId: 'minimal-chat-app-692db',
    storageBucket: 'minimal-chat-app-692db.firebasestorage.app',
    iosBundleId: 'com.example.myChartApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKknzkKsTEzQYkHAhkvvJ0RAfUuLP2NZU',
    appId: '1:838439486018:web:a14c18f8401d8f190c63db',
    messagingSenderId: '838439486018',
    projectId: 'minimal-chat-app-692db',
    authDomain: 'minimal-chat-app-692db.firebaseapp.com',
    storageBucket: 'minimal-chat-app-692db.firebasestorage.app',
  );
}
